### ISSUE TITLE
[Strictly 10.3.0] Encryption 1.4.0

### ISSUE THREAD

**Issue by felixboehm** [owncloud/encryption#17]
**REMINDER:** Please add your name to the checkbox when you have completed an item

### Reason
- Migrate app out of `owncloud/core` repository

### Open Tasks

- [x] code parity https://github.com/owncloud/encryption/issues/118
- [x] translations https://github.com/owncloud/encryption/issues/136

### QA

- [x] Create **QA** Milestone and set the description to $version @patrickjahns 
- [x] Move items from `development` to `qa` @patrickjahns 
- [ ] Create release branch with the format "release-$version" @patrickjahns 
- [x] Create "1.4.0 Testplan" @davitol  https://github.com/owncloud/encryption/issues/142

### Documentation

- [ ] Changes in the docs needed?

### Marketing

- [ ] Ping @owncloud/marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build

All actions to be done on the release branch from here:
- [x] Bump version in info.xml (no version suffix) @patrickjahns 
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version' (final release date unknown) @patrickjahns 

#### Beta/RC

- [x] Create github tag for 'v${version}RC1' on release branch @patrickjahns 
- [x] Build and sign RC tarball from github tag 'v${version}RC1' (see
  handbook for how to build) @patrickjahns 
- [ ] Upload as Github release using changelog entries @patrickjahns 
- [ ] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch  @davitol https://github.com/owncloud/encryption/issues/142

#### Final

- [ ] Create github tag for final 'v${version}' on release branch
- [ ] Build and sign final tarball from github tag 'v${version}' (see
  handbook for how to build)
- [ ] Upload as Github release using changelog entries
- [ ] Smoke test tarball (at least install + enable)

### Publishing

- [ ] ~~Upload tarball to marketplace (see handbook for details)~~ app will not be individually published
- [ ] ~~Publish tarball for customers (see handbook for details)~~ app will not be individually published
- [ ] ~~Send mail to release-coordination with link to this ticket and to the changelog~~ app will not be individually published

### Post-release

- [ ] Rename QA milestone to '$version'
- [ ] Add a new 'Unreleased' section in CHANGELOG.md and add release date '$version - $currentDate' (ex: 3.1.5 - 2018-08-01)
- [ ] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number

**Comment by PVince81** [comment]
Added "- [ ] have core use this repo's stable10 when bundling".

**Comment by PVince81** [comment]
@felixboehm encryption app is NOT ready for testing. The shipped encryption code is still PR'd into core's stable10, so to test the latest encryption code one needs to test stable10 directly.

Last time we tried to decouple encryption there were some issues, so I expect it won't be a trivial task to do the decoupling in question.

If you say releasing encryption app is of higher priority I could take care of this now...

At this point I personally think there are other apps that we should unbundle first, see https://github.com/owncloud/core/issues/27542

**Comment by felixboehm** [comment]
ok, thanks! No need to hurry, release with 10.0.4 is fine.

**Comment by patrickjahns** [comment]
@felixboehm @PVince81 
anything needed here?

**Comment by PVince81** [comment]
@patrickjahns nothing to be released so far. We need to unbundle encryption from stable10 at some point. Not ready.

**Comment by PVince81** [comment]
since there is no plan yet for marketplace release, we should do a Github release instead and bundle said release with the core release as part of the release script (we already do so for other apps like external, user_external, etc)

Raised https://github.com/owncloud/encryption/issues/118 to get the branches aligned

**Comment by patrickjahns** [comment]
Updated top post with latest template - pushing for a github releases

**Comment by patrickjahns** [comment]
According to https://github.com/owncloud/encryption/issues/118#issuecomment-517134308 - we can move forward with the github release of this app

**Comment by PVince81** [comment]
final tarball here: https://github.com/owncloud/encryption/releases/tag/v1.4.0

**Comment by PVince81** [comment]
PR for merge back: https://github.com/owncloud/encryption/pull/145
