### ISSUE TITLE
HSM daemon integration with Utimaco p11tool2 "duplicate attribute"

### ISSUE THREAD

**Issue by MihaS-CREA** [owncloud/encryption#180]
I seem to have stumbled upon an issue. It's been giving me some trouble for awhile now and I would kindly ask for your support.

When trying to generate a random key the following issue arises:

{"level":"info","ts":"2020-01-28T11:18:25.399Z","caller":"hsmdaemon/keymanager.go:270","msg":"Generating new key pair","label ":"test"}
{"level":"debug","ts":"2020-01-28T11:18:25.399Z","caller":"hsmdaemon/keymanager.go:27","msg":"initialize pkcs11 module","modu le":"/home/creaplus/libcs_pkcs11_R2.so"}
{"level":"debug","ts":"2020-01-28T11:18:25.404Z","caller":"hsmdaemon/keymanager.go:205","msg":"openHSMSession","slotID":1}
{"level":"debug","ts":"2020-01-28T11:18:25.490Z","caller":"hsmdaemon/keymanager.go:290","msg":"created new session"}
{"level":"error","ts":"2020-01-28T11:18:25.491Z","caller":"hsmdaemon/keymanager.go:346","msg":"failed to generate keypair","t okenID":"e6cbe9f7-41bf-11ea-a9cb-00155d00b512","stacktrace":"main.GenerateKeyPair\n\t/home/jfd/Repositories/hsmdaemon/keymana ger.go:346\nmain.genkey\n\t/home/jfd/Repositories/hsmdaemon/hsmdaemon.go:43\nmain.(*Service).Manage\n\t/home/jfd/Repositories /hsmdaemon/hsmdaemon.go:110\nmain.main\n\t/home/jfd/Repositories/hsmdaemon/hsmdaemon.go:245\nruntime.main\n\t/usr/local/go/sr c/runtime/proc.go:201"}
{"level":"error","ts":"2020-01-28T11:18:25.493Z","caller":"hsmdaemon/hsmdaemon.go:247","msg":"Error: ","error":"pkcs11: 0xD1:  CKR_TEMPLATE_INCONSISTENT","stacktrace":"main.main\n\t/home/jfd/Repositories/hsmdaemon/hsmdaemon.go:247\nruntime.main\n\t/us r/local/go/src/runtime/proc.go:201"}

I've checked the log and it seems there is a duplicate attribute happening at CKA_EXTRACTABLE: 

@(#) cxi_api 1.7.7 (Aug 21 2018)
28.01.2020 11:18:25 | [00000680:00000680] C_GetTokenInfo                   | T: leave...
28.01.2020 11:18:25 | [00000680:00000680] C_Login                          | T: enter...
28.01.2020 11:18:25 | [00000680:00000680] C_Login                          | D: session handle: 0x01b341e8
28.01.2020 11:18:25 | [00000680:00000680] C_Login                          | D: user type: 0x00000001
28.01.2020 11:18:25 | [00000680:00000680] C_Login                          | T: leave...
28.01.2020 11:18:25 | [00000680:00000680] C_GenerateKeyPair                | T: enter...
28.01.2020 11:18:25 | [00000680:00000680] checkDuplicates                  | E: Duplicate attribute CKA_EXTRA                                            CTABLE provided.
28.01.2020 11:18:25 | [00000680:00000680] C_GenerateKeyPair                | E: Error CKR_TEMPLATE_INCONSISTE                                            NT occurred.
28.01.2020 11:18:25 | [00000680:00000680] C_GenerateKeyPair                | T: leave...
28.01.2020 11:18:25 | [00000680:00000680] C_Logout                         | T: enter...
28.01.2020 11:18:25 | [00000680:00000680] C_Logout                         | T: leave...
28.01.2020 11:18:25 | [00000680:00000680] C_CloseSession                   | T: enter...
28.01.2020 11:18:25 | [00000680:00000680] log                              | D: Size: 1
28.01.2020 11:18:25 | [00000680:00000680] log                              | D: Index: 0x01b341e8
28.01.2020 11:18:25 | [00000680:00000680] C_CloseSession                   | D: Close session 0x01b341e8.
28.01.2020 11:18:25 | [00000680:00000680] log                              | D: Size: 0
28.01.2020 11:18:25 | [00000680:00000680] C_CloseSession                   | T: leave...
28.01.2020 11:18:25 | [00000680:00000680] C_Finalize                       | T: enter...
28.01.2020 11:18:25 | [00000680:00000680] C_Finalize                       | T: leave...

Connection to the HSM is fine and it is possible to generate a key via the p11tool. Is there some template that the hsmdaemon uses that I am not aware of? I've tried changing the line 27 in hsmdaemon.toml as well. Unfortunately to no avail. I have installed and am using the hsmdaemon 0.0.7.

**Comment by enbrnz** [comment]
Fixed with new release of `hsmdaemon`
