### ISSUE TITLE
Unnecessary file size overhead

### ISSUE THREAD

**Issue by C0rby** [owncloud/encryption#210]
Consider passing the `OPENSSL_RAW_DATA` argument to `openssl_encrypt` and `pass true for $raw_output` to `hash_hmac()` to store the files in binary instead of base64.
Base64 provides a size overhead of around 35%. Or is there a reason to use base64?

When changing this we should not forget about backwards compatibility for existing setups.

**Comment by C0rby** [comment]
Related issue: https://github.com/owncloud/core/issues/10831

**Comment by mmattel** [comment]
@micbar, I know that this might not be a high prio thing, but a reduction in filesize of about 35% is a reason to think about that. What is your pov?

Adding also @pmaier1

**Comment by micbar** [comment]
@mmattel I put it on the radar.

**Comment by mmattel** [comment]
@micbar I was thinking about a transition.
If this reduces the filesize as described, we could introduce a kind of config setting. This setting would explicit enable this new way, to be set before a new installation enables encryption. If the setting is not present, it works like it currently is. Of course, a procedure should be defined how to get from old to new for those who want to migrate a existing encryption. Just my 2c.

**Comment by micbar** [comment]
@karakayasemi Can you take a look?

**Comment by jvillafanez** [comment]
I don't know if we can reduce the header size somehow. It seems to use around 8k, which is huge for small text files or icons, specially when just a few bytes are being used at the moment. 7.5k or more bytes are wasted just in the header.

As said, I'm not sure if we can do something about it now, but next time we need to something similar, we should plan a proper file format.
