### ISSUE TITLE
Add acceptance tests to check encryption.use_legacy_encoding

### ISSUE THREAD

**Issue by phil-davis** [owncloud/encryption#235]
PR #224 introduced the setting `encryption.use_legacy_encoding`
Related issue: #210 

After PR #224 is merged, all files created in tests will use the new encryption format. That is good for testing that the new encryption format works!

But existing systems will have many existing files that are already encrypted with the original encryption format. We want to be sure that those can still be correctly decrypted.

Add tests that:
- set `encryption.use_legacy_encoding` 
- upload some files (so that there are files stored with the legacy encoding)
- turn off `encryption.use_legacy_encoding` 
- upload more files (that will have the new encoding)
- overwrite some of the legacy-encoded files
- check that all files can be downloaded
- check that sharees can also download the files
- and ... ? think of other interesting stuff

There will need to be quite a few scenarios to cover combinations of the above.

**Comment by dpakach** [comment]
tests added in https://github.com/owncloud/encryption/pull/236. So closing this
cc @phil-davis
