### ISSUE TITLE
[QA] encryption app should be named just "Encryption"

### ISSUE THREAD

**Issue by jnweiger** [owncloud/encryption#251]
Seen in 1.5.0RC1

![image](https://user-images.githubusercontent.com/1108546/110867847-c29b6a00-82c7-11eb-8bdb-2dd2cd7a026c.png)

Why do we call this app a default module? It is not even default-enabled

Expected behaviour: The name is just "Encryption"

**Comment by karakayasemi** [comment]
@jnweiger As far as I understand, Encryption is designed to support applications that implement different encryption modules in the core. However, currently, there is only this application module which implemented as the default one. So, I am not sure about changing the app name.

**Comment by jnweiger** [comment]
thanks understood. It is a hint that it actually is extensible. The term "default" is unfortunate, as our default is "unencrypted" (I look from a different angle)
