### ISSUE TITLE
[QA] decrypt failure when moving from unencrypted external storage to encrypted primary storage

### ISSUE THREAD

**Issue by jnweiger** [owncloud/encryption#254]
Seen with owncloud 10.7.0 RC1 and encryption 1.5.0 RC1 
encryption.use_legacy_mode is false.

* external storage SFTP is mounted with encryption disabled.
* The skeleton files are all encrypted.
* mv the Documents folder with its Example.odt into the SFTP folder
* check in the ftp server manually: `file Example.odt` reports  OpenDocument Text -- the file is unencrypted. OK
* try mv the Documents folder back to the root. It fails with an decrypt error. BAD

![image](https://user-images.githubusercontent.com/1108546/111394835-cb22e480-86bb-11eb-8ec8-1822f72b350a.png)

Expected behaviour: 
 * no decryption is attempted, as this storage is already unencrypted.
 * The contents gets re-encrypted while moving.
 * No random guesswork while producing error messages. It is not a sharing issue, nothing was ever shared here.

**Comment by jnweiger** [comment]
Locale was German. Fömlich. The error message is mixed denglish. Is this fixable? if so, please fork a separate issue, else ignore this comment.

**Comment by jnweiger** [comment]
On a fresh setup, with the same instructions, reproduced a slightly different error:

![image](https://user-images.githubusercontent.com/1108546/111401464-a170ba00-86c9-11eb-830e-7ed497b3b609.png)

**Comment by karakayasemi** [comment]
I think we only changed the way to encoding files. Attempting to encrypt/decrypt files on unencrypted storage seems unrelated from the encoding type change. It may not be a regression. I will look at it.

**Comment by karakayasemi** [comment]
Tried with v1.4.0, it is not a regression. Same error happened in latest release. Need to investigate in more depth.

**Comment by IljaN** [comment]
PR: https://github.com/owncloud/core/pull/38567

Planned for 10.7.1
