### ISSUE TITLE
[QA] files:transfer-ownership fails unless manually decrypted

### ISSUE THREAD

**Issue by jnweiger** [owncloud/encryption#285]
Seen with encryption-1.5.1-rc1 on server 10.7.0

* encryption enabled with "user specific key"
![image](https://user-images.githubusercontent.com/1108546/122464387-13052080-cfb7-11eb-9d0a-5f329395036a.png)

* created user1 and user2, both in group 'group1' 
* inspected user1's files, they are encrypted in binary mode.
* `occ files:transfer-ownership user1 user2` aborts with the following error output:
```
Analysing files of user1 ...
    5 [============================]
Some files are encrypted - please decrypt them first
  /user1/files/Photos-user1/Lake-Constance.jpg
  /user1/files/Photos-user1/Portugal.jpg
  /user1/files/Photos-user1/Teotihuacan.jpg
  /user1/files/Photos-user1/inksc.png
  /user1/files/ownCloud Manual.pdf

In TransferOwnership.php line 283:                     
  Execution terminated.  
```                         

Workaround: `occ encryption:decrypt-all user1` then the transfer succeeds.

According to the last entries of https://github.com/owncloud/QA/blob/master/Server/Test_Plan_Files_Transfer_Ownership.md it should also be possible to transfer without manually decrypting encrypted files.

**Comment by pmaier1** [comment]
As we're talking about user-based encryption here, this is not supposed to work. Also the user-based encryption mode is deprecated and not supported anymore.
