### ISSUE TITLE
[QA] encryption with hsmdaemon works without license, but hsmdaemon is proprietary

### ISSUE THREAD

**Issue by jnweiger** [owncloud/encryption#288]
Seen while testing encryption 1.5.1-rc1 with hsmdaemon-0.0.8 and SoftHSM master (2.6.1+) on server 10.7.0

When installing and enabling hsmdaemon, the encryption app continues to work without an enterprise license.

According to https://doc.owncloud.com/server/admin_manual/configuration/server/security/hsmdaemon/#introduction the hsmdaemon is "provided by ownCloud". Details how to obtain the hsmdaemon are missing. 

If it is intended to work with the ownCloud server community edition, the code of the hsmdaemon should be made publically available.

Expected behaviour: All community edition code is public. Enterprise code should also be public, but protected by an appropriate enterprise license.

**Comment by pmaier1** [comment]
The hsmdaemon is part of ownCloud Enterprise. The code is closed and there's no license check. We keep it simple by only allowing customers to obtain the hsmdaemon via our customer portal.
