### ISSUE TITLE
php-cs-fixer

### ISSUE THREAD

**Issue by mmattel** [owncloud/encryption#31]
@DeepDiver1975 
Any plans to implement ``php-cs-fixer`` as we have in core ?

**Comment by mmattel** [comment]
Any update on this ?

**Comment by mmattel** [comment]
@DeepDiver1975 @patrickjahns any update on this?

**Comment by phil-davis** [comment]
And implement the "standard" ``Makefile`` targets for running unit tests, acceptance tests. Move ``phpunit.xml`` to the root folder...

**Comment by phil-davis** [comment]
The next stage of code check/analysis is ``phan`` - see follow-on issue #80
