### ISSUE TITLE
run tests again with latest core

### ISSUE THREAD

**Issue by individual-it** [owncloud/encryption#317]
revert #316 and  #318 and #322 after oc core 10.9.1 is released

**Comment by phil-davis** [comment]
And similar in user_ldap (which has pipelines that run with user_ldap and encryption together)
Revert https://github.com/owncloud/user_ldap/pull/705

**Comment by phil-davis** [comment]
10.9.1 tarballs have been built and are available at the download site. The "pointer" for `latest` should get updated overnight or tomorrow. When that has happened, I will make the PRs to revert the special 10.9.1RC test settings.

**Comment by phil-davis** [comment]
Reverts done in:
- encryption #323 
- user_ldap https://github.com/owncloud/user_ldap/pull/710
