### ISSUE TITLE
missing -y option in  occ encryption:encrypt-all -y

### ISSUE THREAD

**Issue by cdamken** [owncloud/encryption#33]
### Expected behavior:

To create a script to encrypt automatically:

``` 
#!/bin bash
occ app:enable encryption
occ encryption:enable
occ encryption:select-encryption-type masterkey -y
occ encryption:encrypt-all -y
```

### Actual behavior:

Manually works except for the last command:

```
# occ app:enable encryption
encryption enabled
# occ encryption:enable
Encryption enabled

Default module: OC_DEFAULT_MODULE
# occ encryption:select-encryption-type masterkey -y
Master key successfully enabled.
occ encryption:encrypt-all -y

                                   
  The "-y" option does not exist.  
                                   

encryption:encrypt-all
```

This -y option is possible with other commands, for example:
```
occ encryption:select-encryption-type masterkey -y
```

it would be good to have the option `-y` :
```
occ encryption:encrypt-all -y
``` 

it makes no sense to have the options ` -n ` and  `-q ` if there is no ` -y ` 
```
# occ encryption:encrypt-all --help
Usage:
  encryption:encrypt-all

Options:
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
      --no-warnings     Skip global warnings, show command output only
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Help:
  This will encrypt all files for all users. Please make sure that no user access his files during this process!
```

**Comment by PVince81** [comment]
Any reason why an admin would want to do this ?

Is this to automatically migrate multiple instances to a new setup ?

**Comment by paurakhsharma** [comment]
@PVince81, @cdamken, @voroyam Actually if we do`encrypt-all -n` it just says
 ``You are about to encrypt all files stored in your ownCloud installation.
Depending on the number of available files, and their size, this may take quite some time.
Please ensure that no user accesses their files during this time!
Note: The encryption module you use determines which files get encrypted.``

And just abort the command, and does nothing.
What is the command supposed to do?

**Comment by PVince81** [comment]
@sharidas ^

**Comment by xoxys** [comment]
This is also needed for deployment automation like ansible.

**Comment by pako81** [comment]
PR submitted here owncloud/core#35575 - waiting for review/approval

**Comment by phil-davis** [comment]
The fix was implement in the core repo:
`master` https://github.com/owncloud/core/pull/35575
`stable10` https://github.com/owncloud/core/pull/35605
`release-10.2.1` https://github.com/owncloud/core/pull/35606

An acceptance test in this `encryption` repo was adjusted to reflect the corrected behavior:
https://github.com/owncloud/encryption/pull/133
