### ISSUE TITLE
`phpstan` failing at nightly build

### ISSUE THREAD

**Issue by SagarGi** [owncloud/encryption#385]
### Description

`phpstan` pipeline is failing on nightly build and seems to be a hard failure. Needs some investigation regarding it.

```
Line   lib/Crypto/Encryption.php                                           
 ------ -------------------------------------------------------------------- 
  321    Comparison operation ">" between 0 and 0 is always false.           
         💡 Because the type is coming from a PHPDoc, you can turn off this   
            check by setting treatPhpDocTypesAsCertain: false in your        
            ./phpstan.neon.                                                  
 ------ -------------------------------------------------------------------- 


 [ERROR] Found 1 error                                                          

make: *** [Makefile:112: test-php-phpstan] Error 1
```

Failed Build: https://drone.owncloud.com/owncloud/encryption/2914/2/4

**Comment by phil-davis** [comment]
`Installing phpstan/phpstan (1.10.1)`

https://github.com/phpstan/phpstan/releases/tag/1.10.1

1.10.0 and 1.10.1 were released in the last day. I think that they are reporting a "false positive". 

The code is:
`while (\strlen($data) > 0) {`

And it looks to me that `$data` is an ordinary string that can have a length greater than zero or equal to zero.

**Comment by phil-davis** [comment]
I raised an issue with phpstan
https://github.com/phpstan/phpstan/issues/8938

**Comment by phil-davis** [comment]
@SagarGi I will followup this. If the phpstan issue is not fixed quickly, then I will pin the `phpstan` version to a previous passing version. That will get CI to get past `phpstan` so that we can see if everything else passes.

**Comment by SagarGi** [comment]
> @SagarGi I will followup this. If the phpstan issue is not fixed quickly, then I will pin the `phpstan` version to a previous passing version. That will get CI to get past `phpstan` so that we can see if everything else passes.

sure !!
