### ISSUE TITLE
jQuery Core 1.9 Upgrade Guide

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/encryption#39]
# jQuery Core 1.9 Upgrade Guide

Changes of Note in jQuery 1.9
See the full [upgrade guide at jquery.com](http://jquery.com/upgrade-guide/1.9/)

## Minor

`.click()`

- [ ] js/settings-admin.js
- [ ] js/settings-personal.js

`.attr()`

- [ ] js/settings-admin.js
- [ ] js/settings-personal.js

**Comment by sharidas** [comment]
Below are the steps done for testing. 
Masterkey encryption:
1. Execute `./occ  maintenance:install --admin-user "admin" --admin-pass "admin"; ./occ app:disable enterprise_key; ./occ app:enable user_management; ./occ user:add user1`
2. Login as `admin` and enable encryption app from web ui.
3. Click `Enable server side encryption`
4. Select the masterkey from the drop down.
5. Logout and login back as admin user.
6. Verify the welcome.txt file. Its not encrypted.
7. Modify the welcome.txt file and rechecked. Now its encrypted.

User keys encryption:
1. Execute `./occ  maintenance:install --admin-user "admin" --admin-pass "admin"; ./occ app:disable enterprise_key; ./occ app:enable user_management; ./occ user:add user1`
2. Login as `admin` and enable encryption app from web ui.
3. Click `Enable server side encryption`
4. Select the user keys from the drop down.
5. Logout and login back as admin user.
6. Verify the welcome.txt file. Its not encrypted.
7. Modify the welcome.txt file and rechecked. Now its encrypted.
8. Enable recovery password.
9. Enabled password recovery for `admin` user.
10. Logged in as `user1` enabled password recovery for the user.
11. Navigated through different pages and verified in the personal settings if the settings remained same for encryption and it did. 

Conclusion: This works as expected.

**Comment by sharidas** [comment]
This works as expected.
