### ISSUE TITLE
new user cannot access file on external storage

### ISSUE THREAD

**Issue by individual-it** [owncloud/encryption#43]
with Encryption type: User Specific Key

1. enable external storage and connect `/local_storage`
2. create `user1` & `user2`
3. as `user1` create a file on `/local_storage`
4. make sure `user2` can read the file
5. create `user3`
6. try to access the file as `user3` 
```
{"reqId":"bOFbmO81PcSHHxrXVGeD","level":3,"time":"2018-08-14T10:57:53+00:00","remoteAddr":"127.0.0.1","user":"uu3","app":"no app in context","method":"GET","url":"\/owncloud-core\/remote.php\/dav\/files\/uu3\/local_storage\/new-folder\/New%20text%20file.txt?c=2147484153null&x=32&y=32&forceIcon=0&preview=1","message":"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you."}
```

**Comment by PVince81** [comment]
assuming you mounted the external storage with access for "all users".

This is a known limitation of encryption, like https://github.com/owncloud/core/issues/16332.
We can't setup the share key for user3 as we'd need the password of user1 or user2 to do so (or anyone who already has access to the file).

Won't fix, should be part of https://github.com/owncloud/documentation/issues/4179
