### ISSUE TITLE
Move remaining CI from Travis to drone

### ISSUE THREAD

**Issue by phil-davis** [owncloud/encryption#67]

**Comment by individual-it** [comment]
after #68 merged the only thing I can see that is left is the `app:check-code` check

currently only `./occ app:check-code encryption -c deprecation` would pass other tests are failing see #70 

@dpakach please add a check that runs `./occ app:check-code encryption -c deprecation` same as in https://github.com/owncloud/encryption/blob/master/.travis.yml#L39
