### ISSUE TITLE
Fix the unit tests by creating users with unique names

### ISSUE THREAD

**Issue by sharidas** [owncloud/encryption#79]
The unit tests can cause problems when unique users are not created. 
Hardcoding usernames like `user1` , `user2` etc can cause conflicts with other unit tests which if uses the same username. 
Issue which triggered in core stable10 branch : https://github.com/owncloud/core/issues/33720

**Comment by sharidas** [comment]
PR here https://github.com/owncloud/encryption/pull/82

**Comment by karakayasemi** [comment]
Should be fixed with #82. Closing favor of it.
