### ISSUE TITLE
Encryption integration tests

### ISSUE THREAD

**Issue by PVince81** [owncloud/encryption#9]
1) Move the encryption specific tests from core (if any)
2) Run all core integration tests but with encryption enabled (user key and master key modes)

@SergioBertolinSG

**Comment by DeepDiver1975** [comment]
An easier intermediate approach could be to keep the tests in core but execute them in here on travis.

migth save some time ....

**Comment by SergioBertolinSG** [comment]
Yes, that was my idea.

**Comment by SergioBertolinSG** [comment]
PR for it: https://github.com/owncloud/encryption/pull/10

**Comment by PVince81** [comment]
set to p2 "release blocker" as we should not release this app without the tests in place

**Comment by patrickjahns** [comment]
Encryption app is running tests for quite some time - closing
